### ISSUE TITLE
AutoFPS does not Reach Target FPS

### ISSUE THREAD

**Issue by ypaul123** [ResetXPDR/MSFS_AutoFPS#5] opened 2024-12-19 17:30 UTC
Hello,

I'm a big fan of your software, and been using it since it's inspection.
I was wondering if you could help me with something, though - I set FPS to a certain value (like in the screenshot I chose 72), but autoFPS won't keep it at that FPS and uses a higher FPS instead. Why is that ?
![Microsoft Flight Simulator - 1 38 2 0-12-19](https://github.com/user-attachments/assets/5d2ec3aa-c2c6-4327-abd0-445e502869e2)

Hope you could help me out on this one.
Thanks so much in advance.
Happy holidays !

**Comment by ResetXPDR** [comment] 2024-12-19 19:54
It is because you have set TLOD Min to 100, which the app will set your TLOD to while on the ground, and your system is easily achieving that so you are getting better performance than your target. Either increase this value higher or, preferably, tick the TLOD Min+ checkbox and the app will auto increase your TLOD on the ground if you do have excess FPS headroom like you currently do. The readme covers how this all works in detail, so I suggest you read through that.

**Comment by ResetXPDR** [comment] 2024-12-20 06:36
Closing as the question has been answered and the app is working as designed.

**Closed by ResetXPDR** 2024-12-20 06:36 UTC

**Comment by ResetXPDR** [comment] 2024-12-20 22:26
You are not dumb. It can be a bit tricky to work out what is going on with the app sometimes.
